version: 2.1

executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD

jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            # Build and run unit tests
            echo "Building and running tests..."
            # Run unit tests here

      - persist_to_workspace:
          root: .
          paths:
            - build/
            - test-results/

  deploy:
    executor: my-custom-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Production
          command: |
            # Deploy code to production
            echo "Deploying to production..."

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
