version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/KaviduGimhan/Software-Engineering-Sprint1/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  npm-dev:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm install

workflows:
  my-custom-workflow:
    jobs:
      - npm-dev